vtex-apps/store-theme

manifest.json, pages/pages.json, react/HomePage.js, react/ProductPage.js, react/components/Header.js, react/locales/en-US.json, react/locales/es-AR.json, react/locales/pt-BR.json
Enables extending from external apps
Currently, render does not allow you to define an already defined extension point, so we use an extension container to allow such definitions
=> Adding extension point containers to enable extending from external app

CHANGELOG.md, pages/pages.json, react/HomePage.js, react/ProductPage.js, react/components/GalleryWrapper.js, react/mutations/addToCartMutation.gql, react/mutations/updateItemsMutation.gql
Fix pages.json to be able to use ExtensionContainer again
**Secondary:** Remove mutations which aren't used anymore.
We imported the wrong dependency to use `ExtensionContainer`. 
https://dev--storecomponents.myvtex.com/
=> Fix pages.json to be able to use ExtensionContainer again

CHANGELOG.md, react/ProductPage.js, react/theme.css
Remove redundant Spinner in ProductPage Component
The ProductPage was breaking when the product was loading.
[Access the workspace](http://spinner--storecomponents.myvtex.com)
=> Remove redundant Spinner in ProductPage Component

CHANGELOG.md, react/ProductPage.js, react/StoreTemplate.js
Fix product page padding that is pushing down the product-details component.
Access: https://andre--storecomponents.myvtex.com/ninja-300/p
=> Fix product page padding

CHANGELOG.md, pages/pages.json
Add the RelatedProducts component to the product page
The RelatedProducts component was not being used anywhere.
[Access the workspace](https://related--storecomponents.myvtex.com/samsung-s9/p)
=> Add the RelatedProducts component to the product page

CHANGELOG.md, manifest.json, pages/pages.json
This integration is in `vtex.store` now. Don't need to be here. 
https://login--storecomponents.myvtexdev.com/account/orders#/
=> Remove my-orders integration

CHANGELOG.md, pages/pages.json
Add SearchResult to the brand page
The brand page had no components
[Access the workspace](https://estacio--storecomponents.myvtex.com/samsung/b)
=> Add SearchResult to the brand page

CHANGELOG.md, pages/pages.json
Add the `vtex.login/LoginContent` to the empty extension point on the login page.
The login page was empty.
[Access this workspace](https://logincss--storecomponents.myvtex.com/login), although I'm still working on it and it may be broken at sometimes.
=> Add login content component to login page extension point

CHANGELOG.md, pages/pages.json
Change the name of `CategoriesHighlights` to `CategoriesHightlighted`.
Referenced Pull Requests:
- https://github.com/vtex-apps/store-components/pull/134/
=> Change `CategoriesHighlights` to `CategoriesHightlighted`

CHANGELOG.md, manifest.json
- remove unused dependency `vtex.product-summary`
https://claudivan3--storecomponents.myvtex.com/
=> Remove unused dependency vtex.product-summary

CHANGELOG.md, manifest.json, pages/pages.json
Add the Logo and SearchBar as extensions of the Header.
OBS.: It should be released BEFORE this [PR](https://github.com/vtex-apps/store-components/pull/163).
[Access the workspace.](https://waza3--storecomponents.myvtex.com/)
=> Add Logo and SearchBar as extensions of the Header

CHANGELOG.md, manifest.json, pages/pages.json
Depends on: https://github.com/vtex-apps/telemarketing/pull/8
https://bruno--storecomponents.myvtex.com/
=> Add Telemarketing app to the Header extension point

CHANGELOG.md, manifest.json, pages/pages.json
Move the breadcrumb inside an extension point of the product details.
The breadcrumb need to be inside a element with the class `vtex-page-padding` and since the search result is already containing it's own breadcrumb, 
[Workspace](https://lucas--storecomponents.myvtex.com/nintendo-switch/p).
=> Move breadcrumb inside the product details

CHANGELOG.md, manifest.json, pages/pages.json
Add definitions for the `results/gallery`, `results/filter-navigator`, and `results/gallery/product-summary`.
The search is now being moved to use EP only, instead of directly referencing the components.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/smartphones).
=> Add component definitions for search ep's

CHANGELOG.md, pages/pages.json
Add the product-summary extension in pages.json
Adding an extension in header to  load the product-summary in the minicart
=> Add product-summary extension in header/minicart

CHANGELOG.md, react/IconPack.js
As title says: Add arrow-up icon used in search-result
P.S. Has dependence on [this PR](https://github.com/vtex-apps/dreamstore/pull/103)
https://redesign--storecomponents.myvtex.com/eletronicos/d
=> Add arrow-up icon used in search-result

CHANGELOG.md, manifest.json, store/blocks.json
Override the challenge block on the `store.account` to use the `ProfileChallenge`.
The account path won't have authentication without this.
[Workspace](https://lucas--storecomponents.myvtex.com/) (I can't link the dreamstore).
=> Add profile challenge block

CHANGELOG.md, manifest.json, store/blocks.json
Define blocks of orderPlaced page (and normal header)
If store.orderplaced is not referenced in store-theme's blocks.json, the header and footer on that page do not inherit the props set by store-theme, resulting in an empty and/or unthemed header and footer. Defining the blocks in blocks.json solves this.
Navigate to /checkout/orderPlaced and verify that the footer matches the footer on the homepage.
=> Define blocks of orderPlaced page

CHANGELOG.md, manifest.json, store/blocks.json
Add the `labelListPrice` in the *product-details* and *summary* blocks to permit [these](https://github.com/vtex-apps/store-components/pull/441) changes.
Discount price labels should be flexible and changed in the blocks file.
[Workspace](https://rubacao--storecomponents.myvtex.com/traveler-backpack/p?disableUserLand)
If you want to see other behaviors, edit the blocks in store-theme and use the flag ?disableUserLand in the url.
=> Add labelListPrice props in product-details and summary

store/blocks.json
Current reference to category ids is not compatible with every account. 
The idea of the store theme is to allow anyone to clone it and learn how to use our blocks. With the limitation of the category ids, it is currently not possible.
I've removed the category ids by changing the menu-items type to ``custom``.
=> Feature/new layout/no categories

CHANGELOG.md, manifest.json, store/blocks.json
Show the heart icon of wish list in product details.
In product details screen doesn't show the heart icon to add product in wish list.
[workspace](https://thaynan--storecomponents.myvtex.com/)
=> Show the heart icon of wish list in product details

CHANGELOG.md, store/blocks.jsonc
Product review apps were showing the product review form page as the default layout. The theme should define those pages so it doesn't falls back to the default header and footer of the store.
[Workspace](https://breno3--storecomponents.myvtex.com/new-review)
n/a
---|---
✔️ | Bug fix 
=> Add product review form page

CHANGELOG.md, store/blocks/search.jsonc
The `mobileLayout` prop that can be passed to `search-result` should be more easily found by the users. This aims to showcase it.
The default mobile display option for the search result page is now a grid view:
```
mode1: "small"
mode2: "normal"
```
https://victorhmp--storecomponents.myvtex.com/shirt?map=ft
---| Type of Change
---|---
_ | Bug fix 
✔️| New feature 
=> Showcase search results mobile layout

CHANGELOG.md, store/blocks/home/home.jsonc, store/blocks/product.json
Showcase the new props added to the Shelf component.
Remove `product-add-to-list-button` from the product page.
[storecomponents/victorhmp](https://victorhmp--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
=> Use new props for the Shelf component

CHANGELOG.md, styles/css/vtex.carousel.css, styles/css/vtex.store-components.css
Solve warning of deprecation messages of the [CSS Selectors release](https://vtex.io/docs/releases/2019-week-43-44/css-selectors-deprecation?utm_source=pr).
[Workspace](https://breno--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
=> Remove usage of deprecated selectors

CHANGELOG.md, store/blocks/product.json, styles/css/vtex.store-components.css
Use the API provided by SKU Selector to space variations.
https://breno--storecomponents.myvtex.com/classic-shoes/p
---|---
✔️ | Bug fix 
=> Use the proper API to space sku selector

CHANGELOG.md, store/blocks/search.jsonc
Fixed search content layout when there weren't many products but the filter sidebar was long.
Before:
After:
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing?map=c,c,specificationFilter_52&query=/apparel---accessories/clothing/Black)
---|---
✔️ | Bug fix 
=> Fix search content layout

CHANGELOG.md, store/blocks/header/header.jsonc
Currently the `minicart.v2` used by `store-theme` is not using the default layout defined by `vtex.minicart`.
[Workspace](https://minicartchildren--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
=> Remove custom implementation for minicart.v2

CHANGELOG.md, store/blocks.jsonc
Add `height` on `product-summary-image` so every image has the same dimension.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing?map=c,c&order=OrderByReleaseDateDESC&query=/apparel---accessories/clothing)
---|---
_ | Bug fix 
=> Add `height` on `product-summary-image`.

CHANGELOG.md, manifest.json, store/blocks/home/home.jsonc, styles/css/vtex.rich-text.css, styles/css/vtex.slider-layout.css
Our base Store Theme did not contain any examples on the use of `slider-layout` and was still using `vtex.carousel` in the home page. That would encourage users to keep using the carousel instead of using our composable solution of `list-contex.image-list` + `slider-layout`.
The same problem applies to the `shelf` block, which is now a `list-context.product-list` + `slider-layout`.
[Workspace](https://shelflayout--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
This depends on https://github.com/vtex-apps/product-summary/pull/229
=> Remove Carousel and Shelf in favor of list components

CHANGELOG.md, store/blocks/header/header.jsonc, styles/css/vtex.flex-layout.css, styles/css/vtex.store-components.css, styles/css/vtex.store-header.css
This PR aims to refactor the model header of our theme. It uses the new sticky-layout and replaces the specific `header-row` and `header-spacer` blocks with native ones, such as `flex-layout`.
It also adds a gentle animation when the header sticks to the top of the page and makes it a little bit translucent.
Compare my [workspace](https://kiwi--storecomponents.myvtex.com/) with the [original one](http://storetheme.vtex.com/)
---|---
_ | Bug fix 
✔️ | Technical improvements
=> Refactor header to use native blocks and add some translucency

CHANGELOG.md, styles/css/vtex.store-components.css, styles/css/vtex.store-header.css
- Setting a `max-width` on the `searchBarContainer` breaks the layout on firefox. This PR changes this behavior to limiting the width of the actual input element.
- The logo wasn't being animated when the header got stuck.
- Removed animations for user with `prefers-reduced-motion`
Waiting for: https://github.com/vtex/styleguide/pull/1051
Check the search bars on this workspace in Firefox:
[Workspace](https://kiwisearch--storecomponents.myvtex.com/)
Compare with:
https://storetheme.vtex.com
---|---
✔️  | Bug fix 
=> Select search bar input instead of container and fix header animations 

CHANGELOG.md, manifest.json, store/blocks.jsonc, store/blocks/home/home.jsonc, store/blocks/price.jsonc, store/blocks/product.jsonc, store/blocks/quickview.json, styles/css/vtex.product-price.css, styles/css/vtex.product-summary.css, styles/css/vtex.reviews-and-ratings.css, styles/css/vtex.store-components.css
As the title says. You can see the difference in PDP and on the product summaries.
⚠️**THIS SHOULD NOT BE MERGED UNTIL I BUMP THE `vtex.product-price` VERSION TO 1.X ON THE MANIFEST!**
🔴I SHOULD MAKE THE NECESSARY CHANGES ON SITE-EDITOR WHEN THIS IS MERGED SO EVERY PRODUCT SUMMARY IS HOW IT IS IN THE WORKSPACE'S SHELF
[Workspace](https://productprice--storecomponents.myvtex.com/)
PDP
Shelf
Detailed screenshot
=> Add new `vtex.product-price` blocks.

CHANGELOG.md, store/blocks/search.jsonc
Set `preventRouteChange` to false so our test store can have the new URL format. The side effect of this decision is that without `preventRouteChange`, every facet selection will trigger a page reload.
https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/color_White
Check that the URL is better
---|---
_ | Bug fix 
✔️ | Technical improvements
=> Set `preventRouteChange` to `false`

CHANGELOG.md, docs/README.md, manifest.json
The old URL of [Build a store using VTEX IO] go to 404 page, I changed to the new one that I supposed that is the right one (https://vtex.io/docs/getting-started/build-stores-with-store-framework/1/).
Update the readme to point to the right location in docs.
Just click the new link.
=> Update README to correct docs URL

CHANGELOG.md, styles/configs/style.json
Those colors are out of sync with Figma (from `#dbe9fd` to `#d2defc`).
See https://github.com/vtex-apps/place-components/pull/21#discussion_r462546314.
The changes are the same as https://github.com/vtex/vtex-tachyons/pull/32.
I don't know, as no component use those classnames, but I suppose testing this won't be necessary. It does not break anything though -> [workspace](https://style--storecomponents.myvtex.com/).
=> Fix active action-secondary bg and border colors

CHANGELOG.md, store/blocks/minicart.jsonc
This definition for `icon-cart` is not necessary and was causing the minicart icon to be too big.
[Workspace](https://victormiranda--storecomponents.myvtex.com/)
**Before**
**After**
=> Remove unnecessary 'icon-cart' definition

CHANGELOG.md, store/blocks/minicart.jsonc
The current behavior causes the `minicart.v2` drawer to open even when users are just changing the quantity for an item that is already in the cart.
This was reported by the @vtex-apps/checkout-ui team, and can be reproduced by interacting with the `quantity-selector` at: https://checkoutio.myvtex.com/cart/add?sku=289.
1. Go to this [Workspace](https://victormiranda--checkoutio.myvtex.com/cart).
2. Add a product to the cart and you should see the `minicart.v2` drawer open itself.
3. Click the `Go to checkout` button and go to `/cart`.
4. Update the quantity of this item, now the `minicart.v2` should not open.
=> Prevent minicart opening itself on ALL addToCart events

CHANGELOG.md, manifest.json, store/blocks/about-us.json, styles/css/vtex.store-video.css
This PR adds an example of video block usage to the about us page.
It's the second slide on the [about us](https://icarovideoblock--storecomponents.myvtex.com/about-us) page.
=> Adding video block example to about us page

CHANGELOG.md, styles/css/vtex.store-components.css
When the `search-bar` is in a place that gives more space to grow it breaks the position of the right icon of the block. 
[Workspace](https://virtual404--storecomponents.myvtex.com/default-404)
1. It shouldn't break the current layout of the search-bar
Before
Now
We could also try to position the icon correctly, but this would make the input smaller than space and the remaining area that would like the input would be just an empty space
This gif has nothing to do with this PR, I just liked it.
=> Remove unnecessary max-width definition of search-bar block

CHANGELOG.md, store/blocks/search.jsonc
Improves SEO performance by using `a` tags instead of `button` tags on `fetch-more` and `fetch-previous` buttons on search
[Workspace](https://icarosearchseo--storecomponents.myvtex.com/apparel---accessories)
Related to [https://github.com/vtex-apps/store/pull/524](https://github.com/vtex-apps/store/pull/524)
Related to [https://github.com/vtex-apps/search-result/pull/516](https://github.com/vtex-apps/search-result/pull/516)
=> Improve SEO performance on search pages
