vtex-apps/store-theme

- CHANGELOG.md
- pages/pages.json
- react/components/Header.js
Add a menu of links on the top bar of the store.
https://dev--storecomponents.myvtexdev.com/
> Add menu app on the top bar

- react/components/Header.js
- Fix minicart icon visibility on mobile mode
https://dream-teste--storecomponents.myvtex.com/
> Fix minicart icon visibility on mobile mode

- react/HomePage.js
- react/components/Header.js
- react/theme.css
Fix the header position.
Make the header fixed at the page's top.
https://minicart--storecomponents.myvtex.com/
> Fix header position

- manifest.json
- react/components/Header.js
- react/locales/en-US.json
- react/locales/es-AR.json
- react/locales/pt-BR.json
Add the search bar component to the store
Being able to search for the products 
[workspace](https://dreamstore--storecomponents.myvtex.com/)
> Add the search bar component

- pages/pages.json
- react/ProductPage.js
- react/components/Header.js
- react/locales/en-US.json
- react/locales/es-AR.json
- react/locales/pt-BR.json
- react/package.json
- react/theme.css
Show a toast when add a product to the cart
https://dev--storecomponents.myvtex.com/
>  Show a toast when add a product to the cart

- react/components/Header.js
Make the toolbar responsive
Access: https://andre--storecomponents.myvtex.com/
Pixel 2
iPad
Full
> Add responsive layout to the header

- react/ProductPage.js
Remove non expected behavior of slick slider component into the product details page.
The flex-box propertie was removed from product page to fix non-expected behavior of slick slider.
Non expected behavior of slick slider into the product details page.
[Workspace](https://product-images--storecomponents.myvtex.com/)
> Fix product images responsivity

- manifest.json
- pages/pages.json
- react/StoreTemplate.js
- react/components/Header.js
- react/theme.css
https://dev--storecomponents.myvtex.com/
> Add category menu and fix padding

- CHANGELOG.md
- react/theme.css
https://dev--storecomponents.myvtex.com/
> Fix padding at media queries of product page

- CHANGELOG.md
- manifest.json
- react/theme.css
Fix padding top of product page content
https://dev--storecomponents.myvtex.com/google-pixel2/p
> Fix padding top of product page content

- CHANGELOG.md
- react/components/TopMenu.js
Fix topbar style to positioning in the right way.
Topbar, when scrolled, overlapped the VTEX-Topbar
Access: https://fixtopbar--storecomponents.myvtex.com/
> Fix topbar when scrolled overlapped the VTEX-Topbar

- manifest.json
- pages/pages.json
- react/ProductPage.js
- react/SearchPage.js
- react/components/GalleryWrapper.js
- react/queries/productQuery.gql
Create the Breadcrumbs component
Give to the user the ability to go back to a previous point
[workspace](https://felipe--storecomponents.myvtex.com/smartphones/s)
> Add the Breadcrumbs component

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/Header.js
- react/components/TopMenu.js
- react/components/WrappedSpinner.js
- react/package.json
- react/store-global.css
Added the login component to the Header
Now the user is able to do login
[workspace](https://login--storecomponents.myvtex.com/)
> Integrate the login component

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/components/TopMenu.js
Add integration with vtex.my-orders-app
https://dev--storecomponents.myvtex.com/account
> Add integration with vtex.my-orders-app

- CHANGELOG.md
- manifest.json
> Fix my-orders-app version in manifest.json

- CHANGELOG.md
- manifest.json
- pages/pages.json
Moved store/login/container to vtex.store
https://github.com/vtex-apps/store/pull/23
https://extension--storecomponents.myvtex.com/login
> Moved store/login/container to vtex.store

- manifest.json
- pages/pages.json
Put the ProductKit app into the pages.json DreamStore Theme.
Now, the Product Kit app can be viewed in the Product Page.
> Add ProductKit to pages.json

- CHANGELOG.md
- pages/pages.json
- Add loading extension to pages.json
[workspace](https://claudivan2--storecomponents.myvtex.com/account)
> Add loading extension to pages.json

- CHANGELOG.md
- manifest.json
Bump vtex.styleguide version
https://bruno--storecomponents.myvtex.com/
> Bump vtex.styleguide version

- CHANGELOG.md
- manifest.json
- pages/pages.json
Add the feature of impersonating a customer
Now the telemarketing can impersonate a customer
[workspace](https://impersonate--storecomponents.myvtex.com/)
- [#1](https://github.com/vtex-apps/impersonate-customer/pull/1)
- [#135](https://github.com/vtex-apps/store-components/pull/135)
> Impersonating a customer

- CHANGELOG.md
- manifest.json
- pages/pages.json
https://andre--storecomponents.myvtex.com/
> Rollback rename CategoriesHighlights

- CHANGELOG.md
- manifest.json
- pages/pages.json
Bump major of vtex.category-menu
> Bump major of vtex.category-menu

- CHANGELOG.md
- manifest.json
- pages/pages.json
Update `SearchResult` entry point.
The entrypoint changed from `SearchResult` to `index`
> Update search result entry point

- CHANGELOG.md
- manifest.json
- pages/pages.json
https://carousel--storecomponents.myvtex.com/
> Fix carousel position in home page

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/store-global.css
> Hide routing header of my-orders in mobile mode

- CHANGELOG.md
- react/store-global.css
Added page padding class to allow apps to have the same default padding.
Footer had different padding compared to Shelf.
[Access the worskpace](https://padding--storecomponents.myvtex.com/)
> Added page padding class to allow apps to have the same default padding.

- CHANGELOG.md
- manifest.json
- pages/pages.json
Using the `Header` component  from its new origin
[workspace](https://felipe1--storecomponents.myvtex.com/)
- [storecomponents](https://github.com/vtex-apps/store-components/pull/169)
- [header](https://github.com/vtex-apps/header/pull/1)
> Standalone Header

- CHANGELOG.md
- manifest.json
- pages/pages.json
Add the footer dependency and update the import in the `pages.json`.
The footer is now in a separate app.
[Workspace](https://lucas--storecomponents.myvtex.com/).
> Use the new footer app

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/IconPack.js
Add the `IconPack` component with all icons used by the store components.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/d?map=c%2Cc&rest=Smartphones).
> Add dreamstore icon pack

- CHANGELOG.md
- manifest.json
- react/store-global.css
Align content to header.
Reduce content page padding, so the content follows header alignment
[Access this workspace](https://alignheader--storecomponents.myvtex.com/)
New alignment
> Align content to header

- CHANGELOG.md
- react/IconPack.js
As title says.
All icon-pack is available [HERE](https://62z41r9kqk.codesandbox.io/)
> Add new telemarketing icon

- CHANGELOG.md
- manifest.json
- react/store-global.css
As the title says.
[Workspace](https://stfrontbody--storecomponents.myvtex.com/admin/cms/storefront)
> Added default background to body in order to provide a nicer look on storefront.

- CHANGELOG.md
- manifest.json
- react/store-global.css
https://fabriga--storecomponents.myvtex.com/
> Remove Fabriga font from global.css

- CHANGELOG.md
- manifest.json
- store/blocks.json
https://builder--storecomponents.myvtex.com/
> Everything back to "normal"

- CHANGELOG.md
- manifest.json
- store/blocks.json
Comply with [this PR](https://github.com/vtex-apps/product-details/pull/81) and [this PR](https://github.com/vtex-apps/store-components/pull/278).
I've also let _prettier_ do its things...
*ORDER OF RELEASE*
1. [`store-components`](https://github.com/vtex-apps/store-components/pull/278)
2. [`product-details`](https://github.com/vtex-apps/product-details/pull/81)
3. [`dreamstore`](https://github.com/vtex-apps/dreamstore/pull/120)
Using [this awesome workspace](https://inga--storecomponents.myvtex.com/)
Nah.
> Adding new required blocks for Product Detail

- CHANGELOG.md
- manifest.json
> Fix store dependency

- CHANGELOG.md
- manifest.json
- store/blocks.json
As the title says.
The product specifications was not being rendered. It is related to these PRs: [1](https://github.com/vtex-apps/store-components/pull/288), [2](https://github.com/vtex-apps/product-details/pull/84).
[Workspace](https://bruno--storecomponents.myvtex.com/shirt/p)
> Add product-specifications in product-details block

- CHANGELOG.md
- manifest.json
- store/blocks.json
Also, change the app name to `store-theme`.
https://shelf--storecomponents.myvtex.com/
> Change related-products for shelf.relatedProducts

- manifest.json
- store/blocks.json
Links e rodapé em ingles.
Utilizando os Blocks
Adicao de um infocard no tema
Traducao e nova versao do header
> Store theme en

- manifest.json
- store/blocks.json
Revert premature merge to master, will create a 3.x branch
> Revert "Store theme en"

- manifest.json
- store/blocks.json
> Add product-review blocks

- CHANGELOG.md
- README.md
Changes on read-me. Product kit now under construction
> product kit is now under construction

- CHANGELOG.md
- manifest.json
- store/blocks.json
Add new component Locale Switcher to the store-theme
This PR depends of these ones:
https://github.com/vtex-apps/store-header/pull/89/
https://github.com/vtex-apps/store-components/pull/453
https://github.com/vtex-apps/store-icons/pull/27
[Access this workspace](https://thalyta--storecomponents.myvtex.com/)
> Add localeSwitcher

- CHANGELOG.md
- manifest.json
- store/blocks.json
As the title says.
Should be `From` and `To`.
> Change product price defaults

- CHANGELOG.md
- store/blocks.json
https://filter--storecomponents.myvtex.com/
> use filter navigator v2

- CHANGELOG.md
- store/blocks.json
Add product reviews blocks to PDP.
Add missing example for product review apps.
https://breno--storecomponents.myvtexdev.com/classic-shoes/p?disableUserLand
> Add product review blocks in PDP

- CHANGELOG.md
- store/blocks/header/category-menu.json
Changed some hrefs and ids on the category-menu, which was causing some browsing problems.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
Navigate through clothing, its subcategories and check that you are on the correct page with the results being filtered correctly.
---|---
✔️| Bug fix 
> Fixed some mistakes on the category-menu

- CHANGELOG.md
- manifest.json
- store/blocks/search.jsonc
Added a new prop to the search result so breadcrumb can appear on mobile
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/)
Test on mobile mode
---|---
_ | Bug fix 
> Added `showBreadcrumbsOnMobile` to the`search-result` block

- CHANGELOG.md
- store/blocks/search.jsonc
wrong props were being passed, rermove them, they were causing confusion.
[Workspace](url)
---|---
_ | Bug fix 
> fix usage of props for search-result block

- CHANGELOG.md
- store/blocks/footer/footer.json
Use `flex-layout` to define the `footer` block and fix padding in the Footer component.
[Workspace](https://victorhmp--storecomponents.myvtex.com/)
(ignore the broken header hehe)
---|---
✔️ | Bug fix 
✔️ | Technical improvements
> Footer flex-layout

- README.md
There was no visual guidance to what store-theme is, making it difficult for new people to quickly grasp what is all about.
Preview modified markdown
---|---
_ | Bug fix 
> Add image preview to store theme readme

- .prettierignore
- CHANGELOG.md
- store/blocks/search.jsonc
> fix fetch-more

- CHANGELOG.md
- manifest.json
- store/blocks/product-assembly.jsonc
- store/blocks/product.json
Show Assembly Options in PDP
[Workspace](https://breno--storecomponents.myvtex.com/star-color-top/p)
---|---
_ | Bug fix 
Depends on:
1. https://github.com/vtex-apps/store-resources/pull/54
2. https://github.com/vtex-apps/product-customizer/pull/38
> Add ProductCustomizer to PDP

- CHANGELOG.md
- manifest.json
- sitemap/sitemap.json
https://jey--storecomponents.myvtex.com/sitemap/sitemap-custom.xml
---|---
_ | Bug fix 
> Add sitemap builder with about-us url for examples

- store/blocks/product-assembly.jsonc
Depends on https://github.com/vtex-apps/product-customizer/pull/41
> Use proper inputvalue interface

- CHANGELOG.md
- store/blocks/search.jsonc
Added the `search-fetch-previous` block to the search result.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/top)
---|---
_ | Bug fix 
**NEEDS https://github.com/vtex-apps/search-result/pull/240 TO WORK**
> search-fetch-previous

- manifest.json
- store/blocks.jsonc
- store/blocks/product.json
Make use product-specification-badges and product-summary-specification-badges to show how to better use them with stack-layout
https://badge3--storecomponents.myvtex.com/work-shirt/p
---|---
_ | Bug fix 
> add badge to product and prod-summary

- CHANGELOG.md
- styles/configs/style.json
Stores are using Fabriga as default font for all texts. We don't have permission to use this font in clients' stores and it's not available if it's not installed. So, we must use a default system font.
https://augusto--vtexgame1.myvtex.com/
---|---
_ | Bug fix 
> Change primary font from Fabriga to San Francisco

- manifest.json
[Workspace](url)
---|---
_ | Bug fix 
> Store Theme for IOQA

- CHANGELOG.md
- store/blocks/search.jsonc
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/top?_q=top&map=ft)
Workspace not working right now
---|---
_ | Bug fix 
> PreventRouteChange = true

- CHANGELOG.md
- store/blocks/home/home.jsonc
- store/blocks/search.jsonc
https://fidelis--storecomponents.myvtex.com/classic?_q=classic&map=ft
---|---
_ | Bug fix 
> use skusFilter

- CHANGELOG.md
- manifest.json
We fixed the builder to not allow an app to use interfaces from indirect dependencies.
This PR introduces the missing dependencies.
[Workspace](https://breno--storecomponents.myvtex.com/)
---|---
✔️ | Bug fix 
> Add missing dependencies

- CHANGELOG.md
- manifest.json
- store/blocks.jsonc
- store/blocks/header/header.json
- store/blocks/header/header.jsonc
- store/blocks/product.json
- styles/css/vtex.product-identifier.css
Use the new flexible `minicart.v2`.
[Workspace](https://minicart--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
> Use new minicart

- CHANGELOG.md
- manifest.json
https://app.clubhouse.io/vtex/story/27271/start-blocking-bad-css
Inapplicable.
See https://github.com/vtex/builder-hub/pull/808
---|---
_ | Bug fix 
✔️ | Technical improvements
> Update styles builder to 2.x

- CHANGELOG.md
- store/blocks/header/category-menu.json
- store/blocks/header/header.jsonc
The store navigation was crappy.
https://breno--storecomponents.myvtex.com/
Before | After
---|---
---|---
_ | Bug fix 
> Fix menu links and layout

- CHANGELOG.md
- store/blocks.jsonc
- store/blocks/product.json
https://breno--storecomponents.myvtex.com/star-color-top/p?skuId=2000564
> Remove product identifier and add props to sku-selector

- CHANGELOG.md
- manifest.json
- store/blocks.jsonc
- store/blocks/header/header.jsonc
- store/blocks/product.json
- styles/css/vtex.stack-layout.css
Add the product bookmark interfaces to be an example.
[Workspace](https://breno--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
> Add bookmark

- CHANGELOG.md
- store/blocks.jsonc
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
Needs https://github.com/vtex-apps/store/pull/405
> Add `store.not-found-product` block.

- CHANGELOG.md
- store/blocks/search.jsonc
https://fidelis--storecomponents.myvtex.com/apparel---accessories/clothing/
[Workspace](url)
---|---
_ | Bug fix 
> search use cold price

- docs/README.md
- Fix broken links in main readme
- Remove deprecated apps
Should probably wait #190 🤔 
#trivial
N/A
N/A
> Fix broken links and remove legacy ones

- CHANGELOG.md
- store/blocks.jsonc
> Adds not-found#search block

- manifest.json
- store/blocks.jsonc
- store/blocks/home/home.jsonc
- store/blocks/quickview.json
- store/blocks/search.jsonc
- styles/css/vtex.flex-layout.css
- styles/css/vtex.modal-layout.css
- styles/css/vtex.product-summary.css
- styles/css/vtex.stack-layout.css
- styles/css/vtex.store-components.css
- styles/css/vtex.store-icons.css
[Workspace](https://quickview--storecomponents.myvtex.com/)
---|---
_ | Bug fix 
Depends on https://github.com/vtex-apps/store-link/pull/1
> Add the quickview to the product-summary.shelf block

- CHANGELOG.md
- manifest.json
- store/blocks/header/top-menu.json
We had some problem with the version in IO, so this is just for fixing it.
---|---
_ | Bug fix 
> Fix version

- CHANGELOG.md
- store/blocks/search.jsonc
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
> Add `fetch-more` and `fetch-previous` on mobile.

- CHANGELOG.md
- store/blocks.jsonc
- store/blocks/product.jsonc
- styles/css/vtex.product-price.css
- styles/css/vtex.product-summary.css
Reference: https://www.figma.com/file/DnpQxbX4N5CsYtr0xdiRRn/02.-Store---Price?node-id=52%3A172
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
> `aspectRatio` on summary and fixed styles.

- CHANGELOG.md
- store/blocks/product-assembly.jsonc
Make input values appear on recursive assemblies
1. Open https://breno--storecomponents.myvtex.com/custom-bell/p
2. Click on Customize
Depends on PR: https://github.com/vtex-apps/product-customizer/pull/60
> Add input values for recursive assemblies

- CHANGELOG.md
- docs/contact-schema.json
- manifest.json
- store/blocks.jsonc
- store/blocks/contact.jsonc
- store/blocks/faq.jsonc
- store/blocks/header/category-menu.json
- store/routes.json
- styles/css/contact/vtex.flex-layout.css
Add an example of usage of store-form.
I added the MasterData v2 schema used in the docs folder (`docs/contact-schema.json`)
Use this form:
https://contact--storecomponents.myvtex.com/contact-us
Then you can make a request to the MasterData v2 API to see that the data is coming in:
```
curl --location --request GET 'https://storecomponents.vtexcommercestable.com.br/api/dataentities/contact/scroll?_fields=title,name,email,message' \
--header 'accept: application/vnd.vtex.ds.v10+json' \
--header 'content-type: application/json' \
--header 'VtexIdClientAutCookie: ADDDDDDDDDDD-YOURRRRRRR-COOKIE-HERE-PLEASE' 
```
> Add Contact us page

- CHANGELOG.md
- manifest.json
- store/blocks/pdp/product-specifications-table.jsonc
- store/blocks/pdp/product.jsonc
- styles/css/product-specification-table/vtex.flex-layout.css
- styles/css/product-specification-table/vtex.product-specifications.css
- styles/css/vtex.reviews-and-ratings.css
- Use product-specifications
- Use the latest version of reviews-and-ratings app
That's a new major version of the app since we are adding a peerDependency
https://filterspec--storecomponents.myvtex.com/classic-shoes/p
n/a
> Add product specifications and migrate reviews-and-ratings

- CHANGELOG.md
- manifest.json
- store/blocks/orderplaced.jsonc
Update store-theme to be the canonical example.
https://orderplaced--storecomponents.myvtex.com/checkout/orderPlaced/?og=1076291795845
> Update order-placed to major 2

- .gitignore
Remove .eslintrc from .gitignore
> Update .gitignore #trivial

- CHANGELOG.md
- store/blocks/pdp/product.jsonc
> Fix PDP not being displayed due to conditional-layout typos
